export const UPLOAD_IMAGE_REQUEST_SEND = "UPLOAD_IMAGE_REQUEST_SEND";
export const UPLOAD_IMAGE_REQUEST_SUCCESS = "UPLOAD_IMAGE_REQUEST_SUCCESS";
export const UPLOAD_IMAGE_REQUEST_FAIL = "UPLOAD_IMAGE_REQUEST_FAIL";
export const SELECT_IMAGE = "SELECT_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const SELECT_FOLDER = "SELECT_FOLDER";
export const ADD_LIST_FOLDER = "ADD_LIST_FOLDER";
export const IMAGE_SELECTION_ERROR = "IMAGE_SELECTION_ERROR";
export const UPLOAD_IMAGE_DONE = "UPLOAD_IMAGE_DONE";

export const IMAGE_GALLEY_MARK_SELECT = "IMAGE_GALLEY_MARK_SELECT";
export const IMAGE_GALLEY_MARK_REMOVE = "IMAGE_GALLEY_MARK_REMOVE";
export const IMAGE_GALLEY_MARK_REMOVE_ALL = "IMAGE_GALLEY_MARK_REMOVE_ALL";

export const IMAGE_GALLEY_LIST_REQUEST_SEND = "IMAGE_GALLEY_LIST_REQUEST_SEND";
export const IMAGE_GALLEY_LIST_REQUEST_SUCCESS =
  "IMAGE_GALLEY_LIST_REQUEST_SUCCESS";
export const IMAGE_GALLEY_LIST_REQUEST_FAIL = "IMAGE_GALLEY_LIST_REQUEST_FAIL";

export const IMAGE_FOLDER_LIST_REQUEST_SEND = "IMAGE_FOLDER_REQUEST_SEND";
export const IMAGE_FOLDER_LIST_REQUEST_SUCCESS = "IMAGE_FOLDER_REQUEST_SUCCESS";
export const IMAGE_FOLDER_LIST_REQUEST_FAIL = "IMAGE_FOLDER_REQUEST_FAIL";
export const IMAGE_FOLDER_LIST_ADD = "IMAGE_FOLDER_LIST_ADD";

export const IMAGE_FOLDER_ADD_REQUEST_SEND = "IMAGE_FOLDER_ADD_REQUEST_SEND";
export const IMAGE_FOLDER_ADD_REQUEST_SUCCESS =
  "IMAGE_FOLDER_ADD_REQUEST_SUCCESS";
export const IMAGE_FOLDER_ADD_REQUEST_FAIL = "IMAGE_FOLDER_ADD_REQUEST_FAIL";

//banner
export const BANNER_REQUEST_SEND = "BANNER_REQUEST_SEND";
export const BANNER_REQUEST_SUCCESS = "BANNER_REQUEST_SUCCESS";
export const BANNER_REQUEST_FAIL = "BANNER_REQUEST_FAIL";
export const BANNER_REQUEST_ADD = "BANNER_REQUEST_ADD";
export const OPEN_EDIT_PAGE = "OPEN_EDIT_PAGE";

export const BANNER_ADD_REQUEST_SENT = "BANNER_ADD_REQUEST_SENT";
export const BANNER_ADD_REQUEST_FAIL = "BANNER_ADD_REQUEST_FAIL";
export const BANNER_ADD_REQUEST_SUCCESS = "BANNER_ADD_REQUEST_SUCCESS";
export const BANNER_MESSAGE_CLEAR = "BANNER_MESSAGE_CLEAR";
export const BANNER_FILTER_SELECT = "BANNER_FILTER_SELECT";

export const EDIT_BANNER_REQUEST_SEND = "EDIT_BANNER_REQUEST_SEND";
export const EDIT_BANNER_REQUEST_SUCCESS = "EDIT_BANNER_REQUEST_SUCCESS";
export const GET_EDITED_BANNER = "GET_EDITED_BANNER";
export const EDIT_BANNER_REQUEST_FAIL = "EDIT_BANNER_REQUEST_FAIL";

export const DELETE_BANNER_REQUEST_SEND = "DELETE_BANNER_REQUEST_SEND";
export const DELETE_BANNER_REQUEST_SUCCESS = "DELETE_BANNER_REQUEST_SUCCESS";
export const DELETE_BANNER_REQUEST_FAIL = "DELETE_BANNER_REQUEST_FAIL";

// CAR TYPE

export const ADD_CAR_TYPE_REQUEST_SEND = "ADD_CAR_TYPES_REQUEST_SEND";
export const ADD_CAR_TYPE_REQUEST_SUCCESS = "ADD_CAR_TYPES_REQUEST_SUCCESS";
export const ADD_CAR_TYPE_REQUEST_FAIL = "ADD_CAR_TYPES_REQUEST_FAIL";

export const GET_CAR_TYPES_REQUEST_SEND = "GET_CAR_TYPE_REQUEST_SEND";
export const GET_CAR_TYPES_REQUEST_SUCCESS = "GET_CAR_TYPE_REQUEST_SUCCESS";
export const CLEAR_SUCCESS_MESSAGE = "CLEAR_SUCCESS_MESSAGE";
export const GET_CAR_TYPES_REQUEST_FAIL = "GET_CAR_TYPE_REQUEST_FAIL";

export const DELETE_CAR_TYPE_REQUEST_SEND = "DELETE_CAR_TYPE_REQUEST_SEND";
export const DELETE_CAR_TYPE_REQUEST_SUCCESS =
  "DELETE_CAR_TYPE_REQUEST_SUCCESS";
export const DELETE_CAR_TYPE_REQUEST_FAIL = "DELETE_CAR_TYPE_REQUEST_FAIL";

export const EDIT_CAR_TYPE_REQUEST_SEND = "EDIT_CAR_TYPE_REQUEST_SEND";
export const EDIT_CAR_TYPE_REQUEST_SUCCESS = "EDIT_CAR_TYPE_REQUEST_SUCCESS";
export const GET_UPDATE_CAR_DATA = "GET_UPDATE_CAR_DATA";
export const EDIT_CAR_TYPE_REQUEST_FAIL = "EDIT_CAR_TYPE_REQUEST_FAIL";

export const GET_SINGLE_CAR_TYPE_REQUEST_SEND =
  "GET_SINGLE_CAR_TYPE_REQUEST_SEND";
export const GET_SINGLE_CAR_TYPE_REQUEST_SUCCESS =
  "GET_SINGLE_CAR_TYPE_REQUEST_SUCCESS";
export const GET_SINGLE_CAR_TYPE_REQUEST_FAIL =
  "GET_SINGLE_CAR_TYPE_REQUEST_FAIL";

// COLOR

export const ADD_COLOR_REQUEST_SEND = "ADD_COLOR_REQUEST_SEND";
export const ADD_COLOR_REQUEST_SUCCESS = "ADD_COLOR_REQUEST_SUCCESS";
export const ADD_COLOR_REQUEST_FAIL = "ADD_COLOR_REQUEST_FAIL";
export const ADD_COLOR_IN_COLOR_LIST = "ADD_COLOR_IN_COLOR_LIST";

export const GET_COLORS_REQUEST_SEND = "GET_COLORS_REQUEST_SEND";
export const GET_COLORS_REQUEST_SUCCESS = "GET_COLORS_REQUEST_SUCCESS";
export const GET_COLORS_REQUEST_FAIL = "GET_COLORS_REQUEST_FAIL";

export const EDIT_COLOR_REQUEST_SUCCESS = "EDIT_COLOR_REQUEST_SUCCESS";
export const EDIT_COLOR_REQUEST_FAIL = "EDIT_COLOR_REQUEST_FAIL";
export const EDIT_COLOR_REQUEST_SEND = "EDIT_COLOR_REQUEST_SEND";
export const GET_UPDATE_COLOR_DATA = "GET_UPDATE_COLOR_DATA";

// YEAR

export const ADD_YEAR_REQUEST_SEND = "ADD_YEAR_REQUEST_SEND";
export const ADD_YEAR_REQUEST_SUCCESS = "ADD_YEAR_REQUEST_SUCCESS";
export const ADD_YEAR_REQUEST_FAIL = "ADD_YEAR_REQUEST_FAIL";
export const GET_ADDED_YEAR_DATA = "GET_ADDED_YEAR_DATA";

export const GET_ALL_YEARS_REQUEST_SEND = "GET_ALL_YEARS_REQUEST_SEND";
export const GET_ALL_YEARS_REQUEST_SUCCESS = "GET_ALL_YEARS_REQUEST_SUCCESS";
export const GET_ALL_YEARS_REQUEST_FAIL = "GET_ALL_YEARS_REQUEST_FAIL";

export const EDIT_YEAR_REQUEST_SEND = "EDIT_YEAR_REQUEST_SEND";
export const EDIT_YEAR_REQUEST_SUCCESS = "EDIT_YEAR_REQUEST_SUCCESS";
export const EDIT_YEAR_REQUEST_FAIL = "EDIT_YEAR_REQUEST_FAIL";
export const UPDATE_EDITED_YEAR_DATA = "UPDATE_EDITED_YEAR_DATA";

// ADMIN ROLE

export const CREATE_ADMIN_ROLE_REQUEST_SEND = "CREATE_ADMIN_ROLE_REQUEST_SEND";
export const CREATE_ADMIN_ROLE_REQUEST_SUCCESS =
  "CREATE_ADMIN_ROLE_REQUEST_SUCCESS";
export const CREATE_ADMIN_ROLE_REQUEST_FAIL = "CREATE_ADMIN_ROLE_REQUEST_FAIL";
export const GET_CREATED_ADMIN_ROLE = "GET_CREATED_ADMIN_ROLE";

export const GET_ALL_ROLE_REQUEST_SEND = "GET_ALL_ROLE_REQUEST_SEND";
export const GET_ALL_ROLE_REQUEST_SUCCESS = "GET_ALL_ROLE_REQUEST_SUCCESS";
export const GET_ALL_ROLE_REQUEST_FAIL = "GET_ALL_ROLE_REQUEST_FAIL";

export const EDIT_ADMIN_ROLE_REQUEST_SEND = "EDIT_ADMIN_ROLE_REQUEST_SEND";
export const EDIT_ADMIN_ROLE_REQUEST_SUCCESS =
  "EDIT_ADMIN_ROLE_REQUEST_SUCCESS";
export const EDIT_ADMIN_ROLE_REQUEST_FAIL = "EDIT_ADMIN_ROLE_REQUEST_FAIL";
export const GET_UPDATE_ADMIN_ROLE = "GET_UPDATE_ADMIN_ROLE";

export const DELETE_ROLE_REQUEST_SEND = "DELETE_ROLE_REQUEST_SEND";
export const DELETE_ROLE_REQUEST_SUCCESS = "DELETE_ROLE_REQUEST_SUCCESS";
export const DELETE_ROLE_REQUEST_FAIL = "DELETE_ROLE_REQUEST_FAIL";

export const RESTORE_ROLE_REQUEST_SEND = "RESTORE_ROLE_REQUEST_SEND";
export const RESTORE_ROLE_REQUEST_SUCCESS = "RESTORE_ROLE_REQUEST_SUCCESS";
export const RESTORE_ROLE_REQUEST_FAIL = "RESTORE_ROLE_REQUEST_FAIL";

// PARTNER

export const ADD_PARTNER_REQUEST_SEND = "ADD_PARTNER_REQUEST_SEND";
export const ADD_PARTNER_REQUEST_SUCCESS = "ADD_PARTNER_REQUEST_SUCCESS";
export const ADD_PARTNER_REQUEST_FAIL = "ADD_PARTNER_REQUEST_FAIL";

export const GET_ALL_PARTNER_REQUEST_SEND = "GET_ALL_PARTNER_REQUEST_SEND";
export const GET_ALL_PARTNER_REQUEST_SUCCESS =
  "GET_ALL_PARTNER_REQUEST_SUCCESS";
export const GET_ALL_PARTNER_REQUEST_FAIL = "GET_ALL_PARTNER_REQUEST_FAIL";

export const UPDATE_SEARCH_KEY = "UPDATE_SEARCH_KEY";
export const UPDATE_STATUS_KEY = "UPDATE_STATUS_KEY";
export const UPDATE_CREATED_BY_KEY = "UPDATE_CREATED_BY_KEY";

export const EDIT_PARTNER_REQUEST_SEND = "EDIT_PARTNER_REQUEST_SEND";
export const EDIT_PARTNER_REQUEST_SUCCESS = "EDIT_PARTNER_REQUEST_SUCCESS";
export const EDIT_PARTNER_REQUEST_FAIL = "EDIT_PARTNER_REQUEST_FAIL";

// DRIVER

export const ADD_DRIVER_REQUEST_SEND = "ADD_DRIVER_REQUEST_SEND";
export const ADD_DRIVER_REQUEST_SUCCESS = "ADD_DRIVER_REQUEST_SUCCESS";
export const ADD_DRIVER_REQUEST_FAIL = "ADD_DRIVER_REQUEST_FAIL";
export const SET_STATUS_FALSE = "SET_STATUS_FALSE";

export const GET_ALL_DRIVERS_BY_PARTNER_REQUEST_SEND =
  "GET_ALL_DRIVERS_BY_PARTNER_REQUEST_SEND";
export const GET_ALL_DRIVERS_BY_PARTNER_REQUEST_SUCCESS =
  "GET_ALL_DRIVERS_BY_PARTNER_REQUEST_SUCCESS";
export const GET_ALL_DRIVERS_BY_PARTNER_REQUEST_FAIL =
  "GET_ALL_DRIVERS_BY_PARTNER_REQUEST_FAIL";

export const EDIT_DRIVER_REQUEST_SEND = "EDIT_DRIVER_REQUEST_SEND";
export const EDIT_DRIVER_REQUEST_SUCCESS = "EDIT_DRIVER_REQUEST_SUCCESS";
export const EDIT_DRIVER_REQUEST_FAIL = "EDIT_DRIVER_REQUEST_FAIL";

// CAR BRAND

export const ADD_BRAND_REQUEST_SEND = "ADD_BRAND_REQUEST_SEND";
export const ADD_BRAND_REQUEST_SUCCESS = "ADD_BRAND_REQUEST_SUCCESS";
export const ADD_BRAND_REQUEST_FAIL = "ADD_BRAND_REQUEST_FAIL";

export const EDIT_BRAND_REQUEST_SEND = "EDIT_BRAND_REQUEST_SEND";
export const EDIT_BRAND_REQUEST_SUCCESS = "EDIT_BRAND_REQUEST_SUCCESS";
export const EDIT_BRAND_REQUEST_FAIL = "EDIT_BRAND_REQUEST_FAIL";

// BRAND MODEL

export const ADD_MODEL_REQUEST_SEND = "ADD_MODEL_REQUEST_SEND";
export const ADD_MODEL_REQUEST_SUCCESS = "ADD_MODEL_REQUEST_SUCCESS";
export const ADD_MODEL_REQUEST_FAIL = "ADD_MODEL_REQUEST_FAIL";

export const EDIT_MODEL_REQUEST_SEND = "EDIT_MODEL_REQUEST_SEND";
export const EDIT_MODEL_REQUEST_SUCCESS = "EDIT_MODEL_REQUEST_SUCCESS";
export const EDIT_MODEL_REQUEST_FAIL = "EDIT_MODEL_REQUEST_FAIL";

// CAR MODEL COLOR AND YEAR

export const GET_COLORS_YEARS_REQUEST_SEND = "GET_COLORS_YEARS_REQUEST_SEND";
export const GET_COLORS_YEARS_REQUEST_SUCCESS =
  "GET_COLORS_YEARS_REQUEST_SUCCESS";
export const GET_COLORS_YEARS_REQUEST_FAIL = "GET_COLORS_YEARS_REQUEST_FAIL";

// MODEL COLOR

export const ADD_MODEL_COLOR_REQUEST_SEND = "ADD_MODEL_COLOR_REQUEST_SEND";
export const ADD_MODEL_COLOR_REQUEST_SUCCESS =
  "ADD_MODEL_COLOR_REQUEST_SUCCESS";
export const ADD_MODEL_COLOR_REQUEST_FAIL = "ADD_MODEL_COLOR_REQUEST_FAIL";

// MODEL YEAR

export const ADD_MODEL_YEAR_REQUEST_SEND = "ADD_MODEL_YEAR_REQUEST_SEND";
export const ADD_MODEL_YEAR_REQUEST_SUCCESS = "ADD_MODEL_YEAR_REQUEST_SUCCESS";
export const ADD_MODEL_YEAR_REQUEST_FAIL = "ADD_MODEL_YEAR_REQUEST_FAIL";
