export const UPLOAD_IMAGE_REQUEST_SEND = "UPLOAD_IMAGE_REQUEST_SEND";
export const UPLOAD_IMAGE_REQUEST_SUCCESS = "UPLOAD_IMAGE_REQUEST_SUCCESS";
export const UPLOAD_IMAGE_REQUEST_FAIL = "UPLOAD_IMAGE_REQUEST_FAIL";
export const SELECT_IMAGE = "SELECT_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const SELECT_FOLDER = "SELECT_FOLDER";
export const ADD_LIST_FOLDER = "ADD_LIST_FOLDER";
export const IMAGE_SELECTION_ERROR = "IMAGE_SELECTION_ERROR";
export const UPLOAD_IMAGE_DONE = "UPLOAD_IMAGE_DONE";

export const IMAGE_GALLEY_MARK_SELECT = "IMAGE_GALLEY_MARK_SELECT";
export const IMAGE_GALLEY_MARK_REMOVE = "IMAGE_GALLEY_MARK_REMOVE";
export const IMAGE_GALLEY_MARK_REMOVE_ALL = "IMAGE_GALLEY_MARK_REMOVE_ALL";

export const IMAGE_GALLEY_LIST_REQUEST_SEND = "IMAGE_GALLEY_LIST_REQUEST_SEND";
export const IMAGE_GALLEY_LIST_REQUEST_SUCCESS =
  "IMAGE_GALLEY_LIST_REQUEST_SUCCESS";
export const IMAGE_GALLEY_LIST_REQUEST_FAIL = "IMAGE_GALLEY_LIST_REQUEST_FAIL";

export const IMAGE_FOLDER_LIST_REQUEST_SEND = "IMAGE_FOLDER_REQUEST_SEND";
export const IMAGE_FOLDER_LIST_REQUEST_SUCCESS = "IMAGE_FOLDER_REQUEST_SUCCESS";
export const IMAGE_FOLDER_LIST_REQUEST_FAIL = "IMAGE_FOLDER_REQUEST_FAIL";
export const IMAGE_FOLDER_LIST_ADD = "IMAGE_FOLDER_LIST_ADD";

export const IMAGE_FOLDER_ADD_REQUEST_SEND = "IMAGE_FOLDER_ADD_REQUEST_SEND";
export const IMAGE_FOLDER_ADD_REQUEST_SUCCESS =
  "IMAGE_FOLDER_ADD_REQUEST_SUCCESS";
export const IMAGE_FOLDER_ADD_REQUEST_FAIL = "IMAGE_FOLDER_ADD_REQUEST_FAIL";

//banner
export const BANNER_REQUEST_SEND = "BANNER_REQUEST_SEND";
export const BANNER_REQUEST_SUCCESS = "BANNER_REQUEST_SUCCESS";
export const BANNER_REQUEST_FAIL = "BANNER_REQUEST_FAIL";
export const BANNER_REQUEST_ADD = "BANNER_REQUEST_ADD";

// CAR TYPE

export const GET_CAR_TYPE_REQUEST_SEND = "GET_CAR_TYPE_REQUEST_SEND";
export const GET_CAR_TYPE_REQUEST_SUCCESS = "GET_CAR_TYPE_REQUEST_SUCCESS";
export const GET_CAR_TYPE_REQUEST_FAIL = "GET_CAR_TYPE_REQUEST_FAIL";

export const DELETE_CAR_TYPE_REQUEST_SEND = "DELETE_CAR_TYPE_REQUEST_SEND";
export const DELETE_CAR_TYPE_REQUEST_SUCCESS =
  "DELETE_CAR_TYPE_REQUEST_SUCCESS";
export const DELETE_CAR_TYPE_REQUEST_FAIL = "DELETE_CAR_TYPE_REQUEST_FAIL";

export const EDIT_CAR_TYPE_REQUEST_SEND = "EDIT_CAR_TYPE_REQUEST_SEND";
export const EDIT_CAR_TYPE_REQUEST_SUCCESS = "EDIT_CAR_TYPE_REQUEST_SUCCESS";
export const EDIT_CAR_TYPE_REQUEST_FAIL = "EDIT_CAR_TYPE_REQUEST_FAIL";

// COLOR

export const ADD_COLOR_REQUEST_SEND = "ADD_COLOR_REQUEST_SEND";
export const ADD_COLOR_REQUEST_SUCCESS = "ADD_COLOR_REQUEST_SUCCESS";
export const ADD_COLOR_REQUEST_FAIL = "ADD_COLOR_REQUEST_FAIL";

export const GET_COLORS_REQUEST_SEND = "GET_COLORS_REQUEST_SEND";
export const GET_COLORS_REQUEST_SUCCESS = "GET_COLORS_REQUEST_SUCCESS";
export const GET_COLORS_REQUEST_FAIL = "GET_COLORS_REQUEST_FAIL";

export const EDIT_COLOR_REQUEST_SEND = "EDIT_COLOR_REQUEST_SEND";
export const EDIT_COLOR_REQUEST_SUCCESS = "EDIT_COLOR_REQUEST_SUCCESS";
export const EDIT_COLOR_REQUEST_FAIL = "EDIT_COLOR_REQUEST_FAIL";
